---
- hosts: Linux
  roles:
    - packages-predeploy

- hosts: FreeBSD
  roles:
    - jenkinsbsd-predeploy
  tags: jenkins

- hosts: all
  roles:
    - accounts-predeploy

- hosts: Ubuntu
  roles:
    - ecommerce-predeploy
  tags: ecommerce

- hosts: FreeBSD
  roles:
    - jenkinsbsd-predeploy

- hosts: WindowsJenkins
  roles:
    - jenkinswin-predeploy
  tags: jenkinswin

- hosts: WindowsMail
  roles:
    - mail-predeploy
  tags: mail
