---
# tasks file for ssh-predeploy
- name: Include OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      - "default.yml"

- name: deploy ssh key
  authorized_key:
      user: root
      state: present
      key: https://github.com/koalatea.keys

- name: deploy ssh config
  copy:
      src: sshd_config
      dest: /etc/ssh/sshd_config
  notify: Restart sshd
