---
# Author: Micah Martin
# Copy the installer over to the box and run it

- name: Copy Installer
  win_copy:
    src: ../files/installer.exe
    dest: C:\hMailInstaller.exe

- name: Installing hMail
  win_command: C:\hMailInstaller.exe /verysilent

- name: Copying configure script
  win_copy:
    src: Setup-hMail.ps1
    dest: C:\Setup-hMail.ps1

- name: Run script
  script: Setup-hMail.ps1 -domainName "{{ hmail_domain_name }}" -ipAddr "{{ machines[inventory_hostname]['ip'] }}"
    
