---
# Author: Micah Martin
# Copy the installer over to the box and run it

- name: Copy Installer
  win_copy:
    src: ../files/installer.exe
    dest: C:\hMailInstaller.exe

- name: Installing hMail
  win_command: C:\hMailInstaller.exe /verysilent

# Copy the configure script to the server for
- name: Copying configure script
  win_template:
    src: ../templates/configure.j2
    dest: C:\Setup-hMail.ps1

# Execute the script
- name: Running Script
  win_shell: C:\Setup-hMail.ps1

# Remove the script from the system
- name: Removing file
  win_file:
    path: C:\Setup-hMail.ps1
    state: absent
